version: '3.1'
services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: nest
      POSTGRES_PASSWORD: user
      POSTGRES_PASSWORD: 12345
    networks:
      - nest_net

networks:
  nest_net: